apiVersion: ocs.openshift.io/v1
kind: StorageCluster
metadata:
  name: ocs-storagecluster
  namespace: openshift-storage
  annotations:
    ocs.openshift.io/clusterIsDisasterRecoveryTarget: 'true'
spec:
  storageDeviceSets:
    - count: 1
      dataPVCTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 512Gi
          storageClassName: gp3-csi
          volumeMode: Block
      name: ocs-deviceset-gp3-csi
      placement: {}
      portable: true
      replica: 3
      resources:
        limits:
          cpu: '2'
          memory: 5Gi
        requests:
          cpu: '1'
          memory: 5Gi
  encryption:
    clusterWide: false
    enable: false
    kms:
      enable: false
    storageClass: false
  monDataDirHostPath: ''
  resources:
    mds:
      limits:
        cpu: '3'
        memory: 8Gi
      requests:
        cpu: '1'
        memory: 8Gi
    rgw:
      limits:
        cpu: '2'
        memory: 4Gi
      requests:
        cpu: '1'
        memory: 4Gi
  arbiter:
    enable: false
  manageNodes: false
  network:
    connections:
      encryption:
        enabled: false
  nodeTopologies:
    arbiterLocation: ''
  flexibleScaling: false
