DEPLOYMENT:
  force_download_installer: false
  installer_version : "4.12.0-0.nightly"
  ssh_key: "/home/gshanmug/.ssh/id_rsa.pub"
ENV_DATA:
  skip_ocp_deployment: false
  skip_ocs_deployment: false
  ocs_registry_image: "quay.io/rhceph-dev/ocs-registry:latest-stable-4.12.0"
  ocs_csv_channel: "stable-4.12"
  ocs_version: '4.12'
  enable_console_plugin: true
REPORTING:
  email:
    skip_notification: false
